version: "3.9"
services:
  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${SENTRY_DB_USER}
      POSTGRES_PASSWORD: ${SENTRY_DB_PASSWORD}
      POSTGRES_DB: ${SENTRY_DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./sentry:/var/lib/postgresql/data/pgdata

  sentry:
    image: sentry
    links:
      - redis
      - postgres
    ports:
      - 9999:9000
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_DB_NAME: ${SENTRY_DB_NAME}
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379

  cron:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_DB_NAME: ${SENTRY_DB_NAME}
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379

  worker:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_DB_NAME: ${SENTRY_DB_NAME}
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379

  sentry-init:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry upgrade"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_DB_NAME: ${SENTRY_DB_NAME}
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379

  sentry-create-user:
    image: sentry
    links:
      - redis
      - postgres
    command: "sentry createuser"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: ${SENTRY_DB_USER}
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_DB_NAME: ${SENTRY_DB_NAME}
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379
